-- --select transform_payers

{{ config(
    materialized='incremental',
    schema='massachusetts_ehr',
    alias='payers',
    incremental_strategy='append',
    on_schema_change='append_new_columns'
) }}

select 

    ID ,
    NAME ,
    OWNERSHIP ,
    ADDRESS ,
    CITY ,
    STATE_HEADQUARTERED ,
    ZIP ,
    PHONE ,
    AMOUNT_COVERED::NUMBER(15, 2) AS AMOUNT_COVERED,
    AMOUNT_UNCOVERED::NUMBER(15, 2) AS AMOUNT_UNCOVERED,
    REVENUE::NUMBER(15, 2) AS REVENUE,
    COVERED_ENCOUNTERS::INT AS COVERED_ENCOUNTERS,
    UNCOVERED_ENCOUNTERS::INT AS UNCOVERED_ENCOUNTERS,
    COVERED_MEDICATIONS::INT AS COVERED_MEDICATIONS,
    UNCOVERED_MEDICATIONS::INT AS UNCOVERED_MEDICATIONS,
    COVERED_PROCEDURES::INT AS COVERED_PROCEDURES,
    UNCOVERED_PROCEDURES::INT AS UNCOVERED_PROCEDURES,
    COVERED_IMMUNIZATIONS::INT AS COVERED_IMMUNIZATIONS,
    UNCOVERED_IMMUNIZATIONS::INT AS UNCOVERED_IMMUNIZATIONS,
    UNIQUE_CUSTOMERS::INT AS UNIQUE_CUSTOMERS,
    QOLS_AVG::NUMBER(5, 4) AS QOLS_AVG,
    MEMBER_MONTHS::INT AS MEMBER_MONTHS,
    'MASS-EHR'::VARCHAR as PIPELINE_NAME,
    '{{ invocation_id }}'::VARCHAR AS DBT_RUN_ID ,
    '{{ model.name }}'::VARCHAR AS DBT_MODEL_NAME,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS LOAD_TS 
   
from {{ source('massachusetts_ehr', 'PAYERS') }}

