name: mass-ehr-dbt
version: 1.0.0
config-version: 2
profile: mass-ehr-dbt
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  mass-ehr-dbt:
    +materialized: view
