--create databases 
CREATE DATABASE IF NOT EXISTS RAW;
CREATE DATABASE IF NOT EXISTS TRANSFORM;
CREATE DATABASE IF NOT EXISTS "MODEL";

--create schemas 
CREATE SCHEMA IF NOT EXISTS RAW.Massachusetts_EHR;
CREATE SCHEMA IF NOT EXISTS TRANSFORM.Massachusetts_EHR;
CREATE SCHEMA IF NOT EXISTS MODEL.Massachusetts_EHR;
