select "START" from RAW.MASSACHUSETTS_EHR.PROCEDURES limit 100

select "START"::TIMESTAMP from RAW.MASSACHUSETTS_EHR.PROCEDURES limit 100

select * from RAW.MASSACHUSETTS_EHR.PATIENTS

use database raw; 
use schema MASSACHUSETTS_EHR;

select * from ENCOUNTERS
select count(*) from encounters

select * from ENCOUNTERS en
left join PATIENTS pa
on en.patient = pa.id
limit 100

select * from TRANSFORM.MASSACHUSETTS_EHR.ENCOUNTERS

ID
START
STOP
PATIENT
ORGANIZATION
PROVIDER
PAYER
ENCOUNTERCLASS
CODE
DESCRIPTION
BASE_ENCOUNTER_COST
TOTAL_CLAIM_COST
PAYER_COVERAGE
REASONCODE
REASONDESCRIPTION

--drop table TRANSFORM.MASSACHUSETTS_EHR.ENCOUNTERS;
drop schema TRANSFORM.MASSACHUSETTS_EHR_MASSACHUSETTS_EHR

SELECT * from RAW.MASSACHUSETTS_EHR.ENCOUNTERS

SELECT * from TRANSFORM.MASSACHUSETTS_EHR.ENCOUNTERS


